#!/bin/sh
# Created @ 16.10.2010 by TheFox

NAME="phpdl"
VERSION="0.1.0"
TARF="$NAME-$VERSION.tar"
GZIPF="$TARF.gz"
DIRS="img install lib styles tpl"
FILES="build index.php stack.php stackstart stackstop wget.php LICENSE README"


rm -f $TARF $GZIPF
tar -vcf $TARF $DIRS $FILES
gzip $TARF

# EOF
