#!/bin/sh
# Created @ 16.10.2010 by TheFox

export LOG DATE
#LOG=/var/log/scripts/.log
DATE=`date +"%Y/%m/%d %H:%M:%S"`
NAME="phpdl"
VERSION="0.1.0"
TARF="$NAME-$VERSION.tar"
GZIPF="$TARF.gz"
DIRS="img install lib styles tpl"
FILES="build stackstart index.php stack.php wget.php LICENSE README"


#echo "$DATE $USER" >> $LOG
rm -f $TARF $GZIPF
tar -vcf $TARF $DIRS $FILES
gzip $TARF

# EOF
