#!/usr/bin/env bash
# Created @ 07.12.2010 by Christian Mayer <http://fox21.at>

export DATE
DATE=`date +"%Y%m%d"`
SH_SOURCE=`dirname $0`


cd $SH_SOURCE
touch tmp/.stack.php.sd
echo "stack.php will shutdown ..."
