#!/bin/sh
# Created @ 01.11.2010 by TheFox@fox21.at

export DATE
DATE=`date +"%Y%m%d"`
SH_SOURCE=`dirname $0`


cd $SH_SOURCE
php stack.php 1>> log/stack.$DATE.log 2>> log/stack.$DATE.log < /dev/null &
echo stack.php started in background

# EOF
